# SPDX-FileCopyrightText: Red Hat, Inc.
# SPDX-License-Identifier: GPL-2.0-or-later

name: CI
on:
  - push
  - pull_request
env:
  EXPORT_DIR: exported-artifacts
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: fedora-riscv-41
            env: py313
    # container:
    #   image: ghcr.io/ffgan/ovirt-imageio-test:${{matrix.distro}}
    #   # Required to create loop devices.
    #   options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up loop devices
        run: |
          # Create loop devices on the host if they don't exist
          for i in {0..15}; do
            if [ ! -e /dev/loop$i ]; then
              sudo mknod /dev/loop$i b 7 $i
            fi
          done
      - name: start container
        run: |
          podman run -d --name test-container --privileged \
          --device /dev/loop-control \
          $(for i in {0..15}; do echo "--device /dev/loop$i"; done) \
          --security-opt label=disable \
          -v ./:/src:Z \
          ghcr.io/ffgan/ovirt-imageio-test:${{matrix.distro}} sleep infinity

      # We need to run this in order to fix sudo execution.
      # See https://github.com/rocky-linux/sig-cloud-instance-images/issues/56
      - name: Fix sudo
        run: podman exec --user root test-container bash -c  "cd /src && chmod 0400 /etc/shadow"
      - name: Run tests
        run: podman exec --user root test-container bash -c  "cd /src && ci/test.sh ${{matrix.env}}"
  rpm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - fedora-riscv-41
    # container: ghcr.io/ffgan/ovirt-imageio-test:${{matrix.distro}}
    steps:
      - uses: actions/checkout@v4
        with:
          # We need the latest tag for creating rpms.
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: start container
        run: |
          podman run -d --name build-container --privileged \
            -v ./:/src:Z \
            ghcr.io/ffgan/ovirt-imageio-test:${{matrix.distro}} sleep infinity
      - name: Build rpms
        run: podman exec build-container bash -c  "cd /src && ./ci/rpm.sh"

      - name: Install createrepo_c if needed
        shell: bash
        run: podman exec build-container bash -c  "which createrepo_c || dnf install -y createrepo_c"

      - name: Create DNF repository if needed
        shell: bash
        run: podman exec build-container bash -c  "cd /src && test -d ${{env.EXPORT_DIR}}/repodata || createrepo_c ${{env.EXPORT_DIR}}"

      - name: Get distro suffix
        id: eval
        run: |
          distro=$(podman exec build-container bash -c "rpm --eval %{?dist} | cut -d '.' -f 2")
          echo $distro  >> $GITHUB_OUTPUT

      - name: copy artifacts
        run: |
          mkdir -p ${{env.EXPORT_DIR}}
          podman cp build-container:/src/exported-artifacts/ ./${{env.EXPORT_DIR}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpm-${{ steps.eval.outputs.distro }}
          path: ${{env.EXPORT_DIR}}
